### Install & Import Necessary Libraries

In [72]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pycaret.classification import *

from pycaret.classification import ClassificationExperiment

# Hydra
import hydra
from hydra import utils
from omegaconf import OmegaConf
import os

In [73]:
import pycaret
pycaret.__version__

'3.0.4'

In [74]:
# Retrieve Hydra Config
cfg = OmegaConf.load('../config/medical_pre_processing.yaml')

print(cfg)

current_path =  os.getcwd() 

# Change to parent path
parent_dir = os.path.abspath(os.path.join(current_path, os.pardir))

print(parent_dir)

{'dataset': {'data': '/data/raw/02_medical_records.csv'}, 'features': {'drop_features': [], 'numeric_features': ['age', 'resting_BP', 'cholesterol', 'fasting_BS', 'max_HR', 'old_peak'], 'categorical_features': ['gender', 'chest_pain', 'resting_ECG', 'exercise_angina', 'ST_slope'], 'ordinal_features': {'gender': ['F', 'M'], 'exercise_angina': ['No', 'Yes']}, 'target_features': 'cv_issue'}, 'setup': {'train_size': 0.8, 'test_size': 0.2, 'memory': 'None'}, 'file_location': {'generate_pkl': '/app/models/medical_best_tuned_model'}}
c:\Users\Zhang Xiang\Desktop\Year 3\Sem 1\IT3385 Machine Learning Operations - 2\Assignment\MLOPS_ASSIGNMENT_GROUP2_TEAM6

### Read CSV File

In [75]:
import os
from hydra import utils

# @hydra.main(config_path='../config/pre_processing.yaml')
# def read_data(config):

## Read Data
# df = pd.read_csv(r'Datasets\Datasets\02_medical_records.csv')

## Read Data
df = pd.read_csv(parent_dir  + cfg.dataset.data)

# Show first 5 rows
df.head()

# read_data()

,age,gender,chest_pain,resting_BP,cholesterol,fasting_BS,resting_ECG,max_HR,exercise_angina,old_peak,ST_slope,cv_issue
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [76]:
# exp = ClassificationExperiment()

In [78]:
clf10 = setup(data=df, 
            target=cfg.features.target_features,
            session_id=1,
            categorical_features = cfg.features.categorical_features, 
            numeric_features = cfg.features.numeric_features,
            ignore_features =  cfg.features.drop_features,
            ordinal_features = cfg.features.ordinal_features,
            train_size=cfg.setup.train_size,
            memory=cfg.setup.memory,

            # This portion will be adjust frequently & used here only 
            # => Not going to use hydra to setup

            # Normalize Data
            normalize=True,
            # Default removal of outliers
            remove_outliers = True,
            outliers_threshold = 0.05,
            outliers_method = 'iforest',
            
           )

In [79]:
best = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .             12:30:28
Status     . . . . . . . . . . . . . . . . . .  Selecting Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Logistic Regression

In [81]:
# save model to local file system as insurance-pipeline.pkl
save_model(best, parent_dir + cfg.file_location.generate_pkl)

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=None\joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['age', 'resting_BP', 'cholesterol', 'fasting_BS', 'max_HR', 'old_peak'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean',
                                                               verbose='deprecated'))),
                 ('catego...
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=RemoveOutliers(method='iforest',
                                                                n_jobs=1,
                                                                random_state=1,
                                                                threshold=0.05))),
                 ('normalize',
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=StandardScaler(copy=True,
                                                                with_mean=True,
                                                                with_std=True))),
                 ('trained_model',
                  <catboost.core.CatBoostClassifier object at 0x000002C17CD74580>)],
          verbose=False),
 'c:\\Users\\Zhang Xiang\\Desktop\\Year 3\\Sem 1\\IT3385 Machine Learning Operations - 2\\Assignment\\MLOPS_ASSIGNMENT_GROUP2_TEAM6/app/models/medical_best_tuned_model.pkl')